version: 2
registries:
  gradle-plugin-portal:
    type: maven-repository
    url: "https://plugins.gradle.org/m2"
  maven-central:
    type: maven-repository
    url: "https://repo.maven.apache.org/maven2/"
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    open-pull-requests-limit: 25
    registries:
      - gradle-plugin-portal
      - maven-central
    schedule:
      interval: "daily"
      time: "08:00"
      timezone: America/New_York
